# This server configuration will be used by Speakeasy when generating SDKs
openapi: 3.0.2
info:
  title: FastAPI Example
  version: 0.1.0
servers:
  - description: Local server
    url: http://127.0.0.1:8000/