workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
  my-source:
    inputs:
      - location: ./openapi.yaml
      - location: ./another-openapi.yaml
      # .... more openapi documents can be added here
    overlays:
      - location: ./overlay.yaml
      - location: ./another-overlay.yaml
      # .... more openapi overlays can be added here
    transformations:
      # Remove unused components from the OpenAPI document
      - removeUnused: true
      # Filter to include only specific operations
      - filterOperations:
          operations: getPets, createPet
          include: true
      # General cleanup of the OpenAPI document (formatting and style)
      - cleanup: true
    output: ./merged-openapi.yaml
    registry:
      location: registry.speakeasyapi.dev/my-org/my-api
  # more inputs can be added here through `speakeasy configure sources` command
  # ....
  # ....
targets:
  my-target:
    target: python
    source: my-source
    testing:
      enabled: true
      mockServer:
        enabled: false
    codeSamples:
      output: codeSamples.yaml
      registry:
        location: registry.speakeasyapi.dev/my-org/my-api/code-samples
  # more inputs can be added here through `speakeasy configure targets` command
  # ....
  # ....