openapi: 3.0.0

info:
  title: Hitchhiker's Guide to Drinks
  description: An API for creating and retrieving drinks.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /create-drink:
    post:
      operationId: createDrink
      summary: Create a new drink based on provided ingredients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IngredientsRequest"
            example:
              ingredients:
                - Gin
                - Tonic water
                - Lime juice
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DrinkResponse"
              example:
                name: Pan Galactic Gin and Tonic
                description: A refreshing twist on the classic gin and tonic, inspired by the Hitchhiker's Guide to the Galaxy.
                recipe: Fill a glass with ice. Pour in 2 oz of gin, 4 oz of tonic water, and a squeeze of lime juice. Stir gently and garnish with a lime wedge. Enjoy responsibly while contemplating the vastness of the universe.
                photo: https://example.com/pan-galactic-gin-and-tonic.jpg
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error"

  /get-drink:
    post:
      operationId: getDrink
      summary: Get a drink recipe by providing its name
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DrinkNameRequest"
            example:
              name: Pan Galactic Gargle Blaster
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DrinkRecipeResponse"
              example:
                ingredients:
                  - name: Ol' Janx Spirit
                    quantity: 1 bottle
                  - name: Sea water from Santraginus V
                    quantity: 1 measure
                  - name: Acturan Mega-gin
                    quantity: 3 cubes
                  - name: Fallian marsh gas
                    quantity: 4 liters
                  - name: Qualactin Hypermint extract
                    quantity: 1 teaspoon
                recipe: Pour the Ol' Janx Spirit into a glass, add the sea water and Acturan Mega-gin. Bubble the Fallian marsh gas through the mixture, then add the Qualactin Hypermint extract. Drink... but... very carefully.
                photo: https://example.com/pan-galactic-gargle-blaster.jpg
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error"

components:
  schemas:
    IngredientsRequest:
      type: object
      description: A request containing a list of ingredients for creating a new drink.
      properties:
        ingredients:
          type: array
          description: An array of ingredient names as strings.
          example:
            - Gin
            - Tonic water
            - Lime juice
          items:
            type: string
            example: Gin
      required:
        - ingredients

    DrinkResponse:
      type: object
      description: A response containing information about a newly created drink.
      properties:
        name:
          type: string
          description: The name of the drink.
          example: Pan Galactic Gin and Tonic
        description:
          type: string
          description: A brief description of the drink.
          example: A refreshing twist on the classic gin and tonic, inspired by the Hitchhiker's Guide to the Galaxy.
        recipe:
          type: string
          description: The recipe for making the drink.
          example: Fill a glass with ice. Pour in 2 oz of gin, 4 oz of tonic water, and a squeeze of lime juice. Stir gently and garnish with a lime wedge. Enjoy responsibly while contemplating the vastness of the universe.
        photo:
          type: string
          format: uri
          description: A URL pointing to an image of the drink.
          example: https://example.com/pan-galactic-gin-and-tonic.jpg

    DrinkNameRequest:
      type: object
      description: A request containing the name of a drink to retrieve the recipe for.
      properties:
        name:
          type: string
          description: The name of the drink.
          example: Pan Galactic Gargle Blaster
      required:
        - name

    DrinkRecipeResponse:
      type: object
      description: A response containing the recipe and information about a drink.
      properties:
        ingredients:
          type: array
          description: An array of objects representing ingredients and their quantities.
          items:
            $ref: "#/components/schemas/IngredientQuantity"
        recipe:
          type: string
          description: The recipe for making the drink.
          example: Pour the Ol' Janx Spirit into a glass, add the sea water and Acturan Mega-gin. Bubble the Fallian marsh gas through the mixture, then add the Qualactin Hypermint extract. Drink... but... very carefully.
        photo:
          type: string
          format: uri
          description: A URL pointing to an image of the drink.
          example: https://example.com/pan-galactic-gargle-blaster.jpg

    IngredientQuantity:
      type: object
      description: An object representing an ingredient and its quantity.
      properties:
        name:
          type: string
          description: The name of the ingredient.
          example: Ol' Janx Spirit
        quantity:
          type: string
          description: The quantity of the ingredient required.
          example: 1 bottle

    error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      type: object
